### PR TITLE
GBL unit fixes

### LINKED ISSUE #396: GBL Naming
Dear all,

to decouple this a bit from the other threads. Naming. I know this somewhat developed historically, but we have driplets, triplets (I'm Austrian for god's sake, these are the same words!) Furthermorem, triCut, driCut (same again!) and six-cut and many more very unintuitive terms.

If we stick to these terms, we have to explain them somewhere. Maybe it would also be a good time to think about renaming some of them? I don't want to force them being renamed, I'd just like to hear your thoughts and at least get some documentation on them!

### PR DESCRIPTION
**Pull request by tbisanz**
#396

### CODE REVIEW

File: processors/src/EUTelAlignGBL.cc [hunk 1]
```diff
@@ -152,39 +152,31 @@ EUTelAlignGBL::EUTelAlignGBL(): Processor("EUTelAlignGBL") {
...
-  registerOptionalParameter("sixCut", "Upstream-Downstream Track matching cut [um]", _sixCut, 0.60);
-  registerOptionalParameter("slopeCut", "t(d)riplet slope cut [radian]", _slopeCut, 0.01);
-  registerOptionalParameter("GeneratePedeSteerfile","Generate a steering file for the pede program.",_generatePedeSteerfile, 0);
-  registerOptionalParameter("PedeSteerfileName","Name of the steering file for the pede program.",_pedeSteerfileName, string("steer_mille.txt"));
-  registerProcessorParameter("kappa","Global factor to Highland formula", _kappa, 1.0); // 1.0 means HL as is, 1.2 means 20% additional scattering
-
-
+                              _alignModeString, std::string{ "XYShiftsRotZ" });
+  registerOptionalParameter("upstreamTripletResidualCut", "Upstream triplet residual cut [mm]", _upTriResCut, 0.30);
+  registerOptionalParameter("downstreamTripletResidualCut", "Downstream triplet residual cut [mm]", _downTriResCut, 0.40);
```
Comment (edorossi) [inline processors/src/EUTelAlignGBL.cc]: What about setting the same cuts in case the downstream one is not set, as @TCThenna suggested?
```
registerOptionalParameter("upstreamTripletResidualCut", "Upstream triplet residual cut [mm]", _upTriResCut, 0.30);
registerOptionalParameter("downstreamTripletResidualCut", "Downstream triplet residual cut [mm]", _downTriResCut, _upTriResCut);
```

The same for the slopes. I just tested it and it seems to work smoothly.
(edit: I actually don't know if this point belongs here, but it was raised in a parallel discussion)

**Comment by edorossi** [comment]
Looks fine to me!

File: processors/src/EUTelAlignGBL.cc (hunk 1 above)
Comment (tbisanz) [reply processors/src/EUTelAlignGBL.cc]: In my opinion, the problem with that is that if you generate a template it will show:

```
<!-- parameter key="upstreamTripletResidualCut" type=double value="0.30" -->
<!-- parameter key="downstreamTripletResidualCut" type=double value="0.30" -->
```

I.e.. suggesting that 0.30 is the default value if nothing else is set. This is not true however, not for the downstreamTripletResidualCut one at least.

Comment (edorossi) [reply processors/src/EUTelAlignGBL.cc]: Ah, I see the problem. In any case, this was just a minor thing. Moreover, I just realized with the new nomenclature it is clearer that two cuts must be set and there is almost no room for mistake :)

Comment (TCThenna) [reply processors/src/EUTelAlignGBL.cc]: or we set no default at all for the downstreamSlope? 
The value to use heavily depends on the use case, so maybe no defaulted cut here, if this means less confusion ...

File: processors/src/EUTelAlignGBL.cc [hunk 2]
```diff
@@ -152,39 +152,31 @@ EUTelAlignGBL::EUTelAlignGBL(): Processor("EUTelAlignGBL") {
...
+  registerOptionalParameter("upstreamTripletSlopeCut", "Upstream triplet slope cut [mrad]", _upSlopeCut, 10.);
```
Comment (TCThenna) [inline processors/src/EUTelAlignGBL.cc]: We should discuss #401 , as we often have rad*length

Comment (TCThenna) [reply processors/src/EUTelAlignGBL.cc]: https://github.com/eutelescope/eutelescope/blob/master/eutelescope/libraries/src/EUTelTripletGBLUtility.cc#L609

This slope is still in rad.

File: processors/src/EUTelAlignGBL.cc (hunk 1 above)
Comment (tbisanz) [reply processors/src/EUTelAlignGBL.cc]: What exactly do you suggest - set it to a mandatory parameter? I.e. `registerParameter(...)`
